# Generated by Django 2.2.4 on 2019-08-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='price',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='songs',
        ),
        migrations.AddField(
            model_name='song',
            name='url',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='playlist',
            field=models.ManyToManyField(to='playlist.Playlist'),
        ),
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
