# Generated by Django 2.2.4 on 2019-08-15 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0002_auto_20190814_1757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='url',
            new_name='code',
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='playlist',
            field=models.ManyToManyField(to='playlist.Song'),
        ),
    ]
