# Generated by Django 2.2.4 on 2019-08-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0004_auto_20190815_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='playlist',
        ),
        migrations.AddField(
            model_name='usersettings',
            name='playlists',
            field=models.ManyToManyField(to='playlist.Playlist'),
        ),
    ]
